name: Build and push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  tags:
    - v1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Become one with the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          APP_NAME=sleeper
          VERSION=$(git describe --tags --always --dirty)
          IMAGE_BASE=ghcr.io/jamesmcdonald/$APP_NAME
          IMAGE_NAME=$IMAGE_BASE:$VERSION
          LATEST=$IMAGE_BASE:latest

          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $LATEST

          docker push $IMAGE_NAME
          docker push $LATEST
